#!/usr/bin/env python3
# ca_defs.py - Canadian Definitions for EAS-SAMEmon

# Canadian provinces and territories (SS field of PSSCCC)
# Grouped mapping to avoid redundancy (expanded in CA_PROVINCES)
_PROV_GROUPS = {
    'Alberta': ['71', '72', '73', '74', '75', '76', '77', '78', '79'],
    'British Columbia': ['81', '82', '83', '84', '85', '86', '87', '88', '89'],
    'Manitoba': ['08', '51', '52', '53', '54', '55', '56', '57', '58', '59'],
    'New Brunswick': ['15', '16', '17'],
    'Newfoundland and Labrador': ['21', '22', '23', '24', '25', '26', '27', '28', '29'],
    'Northwest Territories': ['94', '95', '96'],
    'Nova Scotia': ['11', '12', '13', '14'],
    'Nunavut': ['97', '98', '99'],
    'Ontario': ['41', '42', '43', '44', '45', '46', '47', '48', '49'],
    'Prince Edward Island': ['18'],
    'Quebec': ['31', '32', '33', '34', '35', '36', '37', '38', '39'],
    'Saskatchewan': ['61', '62', '63', '64', '65', '66', '67', '68'],
    'Yukon': ['91', '92', '93'],
}

CA_PROVINCES = {ss: name for name, codes in _PROV_GROUPS.items() for ss in codes}

CA_SAME_CODE = {
    '08620': 'Lake Winnipegosis, MB',
    '08631': 'Lake Winnipeg - north basin, MB',
    '08632': 'Lake Winnipeg - south basin, MB',
    '08640': 'Lake Manitoba, MB',
    '11100': 'Kings County, NS',
    '11200': 'Annapolis County, NS',
    '11300': 'Digby County, NS',
    '11400': 'Lunenburg County, NS',
    '11500': 'Queens County, NS',
    '11600': 'Shelburne County, NS',
    '11700': 'Yarmouth County, NS',
    '12100': 'Cumberland County - Minas Shore, NS',
    '12200': 'Cumberland County North and Cobequid Pass, NS',
    '12300': 'Colchester County - Cobequid Bay, NS',
    '12400': 'Colchester County North, NS',
    '12500': 'Hants County, NS',
    '12600': 'Colchester County - Truro and south, NS',
    '12700': 'Halifax Metro and Halifax County West, NS',
    '12800': 'Halifax County - east of Porters Lake, NS',
    '13100': 'Pictou County, NS',
    '13200': 'Guysborough County, NS',
    '13300': 'Antigonish County, NS',
    '14100': 'Richmond County, NS',
    '14200': 'Inverness County - south of Mabou, NS',
    '14300': 'Inverness County - Mabou and north, NS',
    '14400': 'Victoria County, NS',
    '14500': 'Sydney Metro and Cape Breton County, NS',
    '15100': 'Fredericton and Southern York County, NB',
    '15200': 'Oromocto and Sunbury County, NB',
    '15300': 'Grand Lake and Queens County, NB',
    '15400': 'Sussex - Kennebecasis Valley and Kings County, NB',
    '15500': 'Saint John and County, NB',
    '15600': 'St. Stephen and Northern Charlotte County, NB',
    '15700': 'Grand Manan and Coastal Charlotte County, NB',
    '16100': 'Woodstock and Carleton County, NB',
    '16200': 'Stanley - Doaktown - Blackville Area, NB',
    '16300': 'Kent County, NB',
    '16400': 'Moncton and Southeast New Brunswick, NB',
    '16500': 'Kouchibouguac National Park, NB',
    '16600': 'Fundy National Park, NB',
    '17100': 'Edmundston and Madawaska County, NB',
    '17210': 'western half of Restigouche County, NB',
    '17220': 'Campbellton and eastern half of Restigouche County, NB',
    '17300': 'Grand Falls and Victoria County, NB',
    '17400': 'Mount Carleton - Renous Highway, NB',
    '17500': 'Bathurst and Chaleur Region, NB',
    '17600': 'Miramichi and area, NB',
    '17700': 'Acadian Peninsula, NB',
    '18100': 'Kings County P.E.I., PE',
    '18200': 'Queens County P.E.I., PE',
    '18300': 'Prince County P.E.I., PE',
    '21100': 'Avalon Peninsula North, NL',
    '21200': 'Avalon Peninsula Southeast, NL',
    '21300': 'St. John\'s and vicinity, NL',
    '21400': 'Avalon Peninsula Southwest, NL',
    '22100': 'Burin Peninsula, NL',
    '22200': 'Connaigre, NL',
    '22300': 'Burgeo - Ramea, NL',
    '22400': 'Channel-Port aux Basques and vicinity, NL',
    '23100': 'Corner Brook and vicinity, NL',
    '23200': 'Deer Lake - Humber Valley, NL',
    '23300': 'Gros Morne, NL',
    '23400': 'Bay St. George, NL',
    '24100': 'Buchans and the interior, NL',
    '24200': 'Grand Falls-Windsor and vicinity, NL',
    '25100': 'Bay of Exploits, NL',
    '25200': 'Bonavista North, NL',
    '25300': 'Bonavista Peninsula, NL',
    '25400': 'Clarenville and vicinity, NL',
    '25500': 'Gander and vicinity, NL',
    '25600': 'Green Bay - White Bay, NL',
    '25700': 'Terra Nova, NL',
    '26100': 'Northern Peninsula East, NL',
    '26200': 'Parson\'s Pond - Hawke\'s Bay, NL',
    '26300': 'Port Saunders and the Straits, NL',
    '27100': 'Red Bay to L\'Anse-au-Clair, NL',
    '27200': 'Norman Bay to Lodge Bay, NL',
    '27300': 'Cartwright to Black Tickle, NL',
    '27400': 'Rigolet and vicinity, NL',
    '27500': 'Postville - Makkovik, NL',
    '27600': 'Hopedale and vicinity, NL',
    '27700': 'Nain and vicinity, NL',
    '28100': 'Upper Lake Melville, NL',
    '28200': 'Eagle River, NL',
    '28300': 'Churchill Valley, NL',
    '29100': 'Churchill Falls and vicinity, NL',
    '29200': 'Labrador City and Wabush, NL',
    '31100': 'Gatineau, QC',
    '31200': 'Waskaganish, QC',
    '31310': 'Joutel - Matagami area, QC',
    '31320': 'Miquelon - Desmaraisville area, QC',
    '31410': 'La Sarre area, QC',
    '31420': 'Amos area, QC',
    '31430': 'Lebel-sur-Quévillon area, QC',
    '31440': 'Senneterre area, QC',
    '31450': 'Rouyn area, QC',
    '31460': 'Malartic area, QC',
    '31470': 'Val d\'Or - Louvicourt area, QC',
    '31510': 'Ville-Marie area, QC',
    '31520': 'Témiscaming area, QC',
    '31610': 'Dorval Lodge area, QC',
    '31620': 'Le Domaine area, QC',
    '31710': 'Rapides-des-Joachims area, QC',
    '31720': 'Fort William - Shawville area, QC',
    '31810': 'Mont-Laurier area, QC',
    '31820': 'La Minerve - Rouge River area, QC',
    '31910': 'Low - Wakefield area, QC',
    '31920': 'Maniwaki - Gracefield area, QC',
    '31930': 'Papineauville - Chénéville area, QC',
    '31940': 'Papineau-Labelle Reserve area, QC',
    '31950': 'Lièvre River area, QC',
    '32110': 'Saint-Michel-des-Saints area, QC',
    '32120': 'Saint-Donat - Mont-Tremblant Park area, QC',
    '32210': 'Mont-Tremblant - Sainte-Agathe area, QC',
    '32220': 'Sainte-Adèle - Saint-Sauveur area, QC',
    '32310': 'Saint-Jérôme area, QC',
    '32320': 'Lachute area, QC',
    '32330': 'Saint-Eustache area, QC',
    '32410': 'Longueuil - Varennes area, QC',
    '32420': 'Laval area, QC',
    '32430': 'Montréal Island area, QC',
    '32440': 'Châteauguay - La Prairie area, QC',
    '32510': 'Soulanges area, QC',
    '32520': 'Vaudreuil area, QC',
    '32530': 'Saint-Rémi area, QC',
    '32540': 'Valleyfield - Beauharnois area, QC',
    '32550': 'Hemmingford area, QC',
    '32560': 'Huntingdon area, QC',
    '32610': 'Berthierville - Saint-Gabriel area, QC',
    '32620': 'Rawdon - Joliette area, QC',
    '32630': 'Mascouche area, QC',
    '32710': 'Louiseville area, QC',
    '32720': 'Matawin - Mauricie National Park area, QC',
    '32730': 'Lac-aux-Sables area, QC',
    '32740': 'Shawinigan area, QC',
    '32750': 'Sainte-Anne-de-la-Pérade area, QC',
    '32760': 'Trois-Rivières area, QC',
    '32811': 'Portneuf area, QC',
    '32812': 'Valcartier - Stoneham area, QC',
    '32813': 'Québec area, QC',
    '32814': 'Côte-de-Beaupré - L\'Île d\'Orléans area, QC',
    '32821': 'Bellechasse area, QC',
    '32822': 'Lévis area, QC',
    '32823': 'Saint-Lambert area, QC',
    '32824': 'Lotbinière area, QC',
    '33100': 'James Bay and La Grande River, QC',
    '33200': 'LG Quatre - Laforge and Fontanges, QC',
    '33300': 'Schefferville, QC',
    '33400': 'Fermont, QC',
    '34100': 'Chibougamau, QC',
    '34210': 'Gouin Reservoir area, QC',
    '34220': 'Parent area, QC',
    '34310': 'Ashuapmushuan Wildlife Reserve area, QC',
    '34320': 'Normandin - Péribonka area, QC',
    '34330': 'Alma - Desbiens area, QC',
    '34340': 'Saint-Félicien - Roberval area, QC',
    '34410': 'Lake Bouchette area, QC',
    '34420': 'La Tuque area, QC',
    '34510': 'Manic-5 area, QC',
    '34520': 'Manic-3 area, QC',
    '34530': 'Chutes-des-Passes - Pipmuacan Reservoir area, QC',
    '34540': 'Labrieville area, QC',
    '34610': 'Forestville area, QC',
    '34620': 'Les Escoumins area, QC',
    '34710': 'Falardeau - Mont-Valin area, QC',
    '34720': 'Sainte-Rose-du-Nord area, QC',
    '34730': 'Ville de Saguenay area, QC',
    '34740': 'Rivière-Éternité - Petit-Saguenay area, QC',
    '34750': 'Tadoussac - Baie-Sainte-Catherine area, QC',
    '34810': 'La Malbaie area, QC',
    '34820': 'Baie-Saint-Paul area, QC',
    '34910': 'Apica Mountain area, QC',
    '34920': 'Grands-Jardins Park area, QC',
    '34930': 'l\'Étape area, QC',
    '35110': 'Mont-Joli area, QC',
    '35120': 'Le Bic - Rimouski area, QC',
    '35130': 'Rimouski Wildlife Reserve area, QC',
    '35200': 'Matane, QC',
    '35310': 'Amqui area, QC',
    '35320': 'Matapédia area, QC',
    '35410': 'Grande-Vallée area, QC',
    '35420': 'Sainte-Anne-des-Monts area, QC',
    '35510': 'Murdochville area, QC',
    '35520': 'Mont-Albert area, QC',
    '35530': 'Grande-Rivière - Cascapédia area, QC',
    '35610': 'New Richmond - Bonaventure area, QC',
    '35620': 'Restigouche - Carleton area, QC',
    '35710': 'Chandler area, QC',
    '35720': 'New Carlisle - Port-Daniel area, QC',
    '35810': 'Forillon National Park - Gaspé area, QC',
    '35820': 'Percé area, QC',
    '36100': 'Baie-Comeau, QC',
    '36210': 'Baie-Trinité area, QC',
    '36220': 'Sept-Îles - Port-Cartier area, QC',
    '36300': 'Minganie, QC',
    '36400': 'Natashquan, QC',
    '36500': 'Chevery, QC',
    '36600': 'Blanc-Sablon, QC',
    '36700': 'Anticosti, QC',
    '36800': 'Îles-de-la-Madeleine, QC',
    '37110': 'Sorel - Yamaska area, QC',
    '37120': 'Saint-Hyacinthe - Acton Vale area, QC',
    '37130': 'Verchères - Beloeil area, QC',
    '37140': 'Saint-Jean - Marieville area, QC',
    '37150': 'Lacolle area, QC',
    '37210': 'Bécancour - Villeroy area, QC',
    '37220': 'Victoriaville area, QC',
    '37230': 'Nicolet area, QC',
    '37240': 'Drummondville area, QC',
    '37311': 'Granby - Waterloo area, QC',
    '37312': 'Brome-Missisquoi area, QC',
    '37321': 'Richmond area, QC',
    '37322': 'Weedon area, QC',
    '37323': 'Thetford Mines area, QC',
    '37331': 'Mont-Orford - Lake Memphrémagog area, QC',
    '37332': 'Sherbrooke area, QC',
    '37333': 'Coaticook area, QC',
    '37334': 'Lac-Mégantic area, QC',
    '37335': 'Cookshire area, QC',
    '37410': 'Lac-Etchemin area, QC',
    '37420': 'Sainte-Marie-de-Beauce area, QC',
    '37430': 'Saint-Georges-de-Beauce area, QC',
    '37510': 'Montmagny - Saint-Jean-Port-Joli area, QC',
    '37520': 'Saint-Fabien - Saint-Pamphile area, QC',
    '37610': 'Trois-Pistoles area, QC',
    '37620': 'Pohénégamook area, QC',
    '37630': 'Kamouraska area, QC',
    '37640': 'Rivière-du-Loup area, QC',
    '37700': 'Témiscouata, QC',
    '38100': 'Ivujivik, QC',
    '38200': 'Akulivik, QC',
    '38300': 'Puvirnituq, QC',
    '38400': 'Inukjuak, QC',
    '38500': 'Umiujaq, QC',
    '38600': 'Kuujjuarapik, QC',
    '39100': 'Salluit, QC',
    '39200': 'Kangiqsujuaq - Raglan Lake, QC',
    '39300': 'Quaqtaq, QC',
    '39400': 'Kangirsuk, QC',
    '39500': 'Aupaluk, QC',
    '39600': 'Tasiujaq, QC',
    '39700': 'Kuujjuaq, QC',
    '39800': 'Kangiqsualujjuaq, QC',
    '41100': 'Simcoe - Delhi - Norfolk, ON',
    '41200': 'Dunnville - Caledonia - Haldimand, ON',
    '41310': 'Watford - Pinery Park - Eastern Lambton County, ON',
    '41320': 'Sarnia - Petrolia - Western Lambton County, ON',
    '41410': 'Chatham-Kent - Rondeau Park, ON',
    '41420': 'Windsor - Leamington - Essex County, ON',
    '41510': 'London - Parkhill - Eastern Middlesex County, ON',
    '41520': 'Strathroy - Komoka - Western Middlesex County, ON',
    '41610': 'St. Thomas - Aylmer - Eastern Elgin County, ON',
    '41620': 'Rodney - Shedden - Western Elgin County, ON',
    '41710': 'Woodstock - Tillsonburg - Oxford County, ON',
    '41720': 'Brantford - County of Brant, ON',
    '42100': 'Attawapiskat, ON',
    '42200': 'Fort Severn, ON',
    '42300': 'Peawanuck, ON',
    '42410': 'Sachigo Lake - Bearskin Lake, ON',
    '42420': 'Big Trout Lake - Kasabonika, ON',
    '42510': 'Sandy Lake - Weagamow Lake - Deer Lake, ON',
    '42520': 'Pikangikum - Poplar Hill - MacDowell, ON',
    '42610': 'Summer Beaver - Wunnummin Lake - Kingfisher Lake, ON',
    '42620': 'Pickle Lake - Cat Lake, ON',
    '42710': 'Webequie, ON',
    '42720': 'Fort Hope - Lansdowne House - Ogoki, ON',
    '43100': 'City of Toronto, ON',
    '43210': 'Uxbridge - Beaverton - Northern Durham Region, ON',
    '43220': 'Newmarket - Georgina - Northern York Region, ON',
    '43230': 'Pickering - Oshawa - Southern Durham Region, ON',
    '43240': 'Vaughan - Richmond Hill - Markham, ON',
    '43310': 'Belleville - Quinte West - Eastern Northumberland County, ON',
    '43320': 'Cobourg - Colborne - Western Northumberland County, ON',
    '43410': 'Tamworth - Sydenham - South Frontenac, ON',
    '43420': 'Stirling - Tweed - Madoc, ON',
    '43510': 'Kingston - Odessa - Frontenac Islands, ON',
    '43520': 'Napanee - Consecon, ON',
    '43530': 'Picton - Sandbanks Park, ON',
    '43610': 'Merrickville-Wolford - Kemptville, ON',
    '43620': 'Westport - Charleston Lake, ON',
    '43630': 'Brockville - Prescott, ON',
    '43640': 'Gananoque - Mallorytown, ON',
    '43710': 'Maxville - Alexandria, ON',
    '43720': 'Cornwall - Lancaster, ON',
    '43730': 'Winchester - Newington, ON',
    '43740': 'Morrisburg - Long Sault, ON',
    '44110': 'Midland - Coldwater - Orr Lake, ON',
    '44120': 'Orillia - Lagoon City - Washago, ON',
    '44130': 'Barrie - Collingwood - Hillsdale, ON',
    '44210': 'South River - Burk\'s Falls, ON',
    '44220': 'Bayfield Inlet - Dunchurch, ON',
    '44310': 'Deep River - Whitney - Eastern Algonquin Park, ON',
    '44320': 'Western Algonquin Park - Lake of Two Rivers, ON',
    '44410': 'Huntsville - Baysville, ON',
    '44420': 'Town of Parry Sound - Rosseau - Killbear Park, ON',
    '44430': 'Port Carling - Port Severn, ON',
    '44440': 'Bracebridge - Gravenhurst, ON',
    '44510': 'Oxtongue Lake - Fort Irwin - Northern Haliburton County, ON',
    '44520': 'Haliburton - Minden - Southern Haliburton County, ON',
    '44610': 'Bancroft - Hastings Highlands - Denbigh, ON',
    '44620': 'Kaladar - Bannockburn - Bon Echo Park, ON',
    '44710': 'Fenelon Falls - Balsam Lake Park - Northern Kawartha Lakes, ON',
    '44720': 'Apsley - Woodview - Northern Peterborough County, ON',
    '44730': 'Lindsay - Southern Kawartha Lakes, ON',
    '44740': 'Peterborough City - Lakefield - Southern Peterborough County, ON',
    '45100': 'Prescott and Russell, ON',
    '45210': 'Petawawa - Pembroke - Cobden, ON',
    '45220': 'Barry\'s Bay - Killaloe, ON',
    '45230': 'Renfrew - Arnprior - Calabogie, ON',
    '45310': 'Smiths Falls - Perth - Eastern Lanark County, ON',
    '45320': 'Plevna - Sharbot Lake - Western Lanark County, ON',
    '45410': 'Ottawa North - Kanata - Orléans, ON',
    '45420': 'Ottawa South - Richmond - Metcalfe, ON',
    '46100': 'City of Hamilton, ON',
    '46210': 'Bruce Peninsula - Sauble Beach - Tobermory, ON',
    '46220': 'Owen Sound - Blue Mountains - Northern Grey County, ON',
    '46230': 'Saugeen Shores - Kincardine - Southern Bruce County, ON',
    '46240': 'Hanover - Dundalk - Southern Grey County, ON',
    '46310': 'Wingham - Blyth - Northern Huron County, ON',
    '46320': 'Listowel - Milverton - Northern Perth County, ON',
    '46330': 'Goderich - Bluewater - Southern Huron County, ON',
    '46340': 'Stratford - Mitchell - Southern Perth County, ON',
    '46410': 'Mount Forest - Arthur - Northern Wellington County, ON',
    '46420': 'Guelph - Erin - Southern Wellington County, ON',
    '46430': 'Kitchener - Cambridge - Region of Waterloo, ON',
    '46510': 'Innisfil - New Tecumseth - Angus, ON',
    '46520': 'Shelburne - Mansfield - Northern Dufferin County, ON',
    '46530': 'Orangeville - Grand Valley - Southern Dufferin County, ON',
    '46610': 'Caledon, ON',
    '46620': 'Mississauga - Brampton, ON',
    '46630': 'Halton Hills - Milton, ON',
    '46640': 'Burlington - Oakville, ON',
    '46710': 'St. Catharines - Grimsby - Northern Niagara Region, ON',
    '46720': 'Niagara Falls - Welland - Southern Niagara Region, ON',
    '47110': 'Red Lake - Woodland Caribou Park, ON',
    '47120': 'Ear Falls - Perrault Falls - Western Lac Seul, ON',
    '47210': 'Savant Lake - Sturgeon Lake, ON',
    '47220': 'Sioux Lookout - Eastern Lac Seul, ON',
    '47310': 'Kenora - Grassy Narrows - Whitedog, ON',
    '47320': 'Sioux Narrows - Nestor Falls - Morson, ON',
    '47410': 'Dryden - Vermilion Bay, ON',
    '47420': 'Ignace - English River, ON',
    '47510': 'Fort Frances - Emo - Rainy River, ON',
    '47520': 'Seine River Village - Mine Centre, ON',
    '48100': 'City of Thunder Bay, ON',
    '48210': 'Armstrong - Auden - Wabakimi Park, ON',
    '48220': 'Beardmore - Jellicoe - Macdiarmid, ON',
    '48230': 'Gull Bay - Black Sturgeon Lake, ON',
    '48310': 'Nakina - Aroland - Pagwa, ON',
    '48320': 'Geraldton - Longlac - Caramat, ON',
    '48330': 'Manitouwadge - Hornepayne, ON',
    '48410': 'Upsala - Raith, ON',
    '48420': 'Atikokan - Shebandowan - Quetico Park, ON',
    '48510': 'Cloud Bay - Dorion, ON',
    '48520': 'Kakabeka Falls - Whitefish Lake - Arrow Lake, ON',
    '48610': 'Nipigon - Rossport, ON',
    '48620': 'Marathon - Schreiber, ON',
    '48710': 'White River - Dubreuilville, ON',
    '48720': 'Wawa - Pukaskwa Park, ON',
    '48810': 'Agawa - Lake Superior Park, ON',
    '48820': 'Searchmont - Montreal River Harbour - Batchawana Bay, ON',
    '48830': 'Sault Ste. Marie - St. Joseph Island, ON',
    '49100': 'Greater Sudbury and vicinity, ON',
    '49200': 'Elliot Lake - Ranger Lake, ON',
    '49310': 'Fort Albany, ON',
    '49320': 'Moosonee, ON',
    '49410': 'Fraserdale - Pledger Lake, ON',
    '49420': 'Kapuskasing - Hearst - Smooth Rock Falls, ON',
    '49510': 'Little Abitibi - Kesagami Lake, ON',
    '49520': 'Timmins - Cochrane - Iroquois Falls, ON',
    '49610': 'Chapleau - Missinaibi Lake, ON',
    '49620': 'Gogama - Foleyet, ON',
    '49710': 'Kirkland Lake - Englehart, ON',
    '49720': 'Temiskaming Shores - Temagami, ON',
    '49810': 'West Nipissing - French River, ON',
    '49820': 'North Bay - Powassan - Mattawa, ON',
    '49910': 'Blind River - Thessalon, ON',
    '49920': 'Espanola - Killarney, ON',
    '49930': 'Manitoulin Island, ON',
    '51110': 'R.M. of Wallace-Woodworth incl. Virden Elkhorn and Kenton, MB',
    '51130': 'Riverdale Mun. incl. Rivers and Wheatland, MB',
    '51140': 'R.M. of Whitehead incl. Alexander and Beresford, MB',
    '51150': 'R.M. of Sifton incl. Oak Lake and Deleau, MB',
    '51160': 'R.M. of Pipestone incl. Oak Lake Res., MB',
    '51170': 'Mun. of Souris-Glenwood, MB',
    '51211': 'R.M. of Elton incl. Forrest, MB',
    '51212': 'R.M. of Cornwallis west of Shilo incl. Chater, MB',
    '51213': 'Mun. of Oakland-Wawanesa incl. Carroll, MB',
    '51220': 'City of Brandon, MB',
    '51231': 'Mun. of North Cypress-Langford incl. Neepawa and Carberry, MB',
    '51232': 'Mun. of Glenboro-South Cypress incl. Treesbank, MB',
    '51241': 'Mun. of North Norfolk incl. MacGregor Sidney and Austin, MB',
    '51242': 'Mun. of Norfolk Treherne, MB',
    '51243': 'R.M. of Victoria incl. Holland and Cypress River, MB',
    '51310': 'Mun. of Grassland incl. Hartney and Minto, MB',
    '51320': 'Mun. of Two Borders incl. Melita Coulter and Tilston, MB',
    '51331': 'Mun. of Brenda-Waskada incl. Medora and Goodlands, MB',
    '51332': 'Mun. of Deloraine-Winchester, MB',
    '51340': 'Mun. of Boissevain-Morton incl. Turtle Mtn Prov. Park, MB',
    '51412': 'Mun. of Killarney-Turtle Mountain, MB',
    '51422': 'R.M. of Argyle incl. Baldur Glenora and Greenway, MB',
    '51431': 'Cartwright-Roblin Mun. incl. Mather, MB',
    '51432': 'Mun. of Louise incl. Pilot Mound and Crystal City, MB',
    '51441': 'Mun. of Lorne incl. Notre Dame and Swan Lake, MB',
    '51442': 'Mun. of Pembina incl. Manitou La Rivière and Snowflake, MB',
    '51450': 'R.M. of Prairie Lakes incl. Margaret Ninette and Belmont, MB',
    '52100': 'City of Winnipeg, MB',
    '52212': 'R.M. of Coldwell incl. Lundar and Clarkleigh, MB',
    '52223': 'R.M. of Gimli incl. Winnipeg Beach and Arnes, MB',
    '52231': 'R.M. of St. Laurent incl. Oak Point, MB',
    '52232': 'R.M. of Woodlands incl. Warren and Lake Francis, MB',
    '52240': 'R.M. of Rockwood incl. Teulon Stonewall and Stony Mountain, MB',
    '52251': 'R.M. of Rosser incl. Meadows, MB',
    '52252': 'R.M. of West St. Paul incl. Middlechurch and Rivercrest, MB',
    '52260': 'R.M. of Armstrong incl. Chatfield Inwood and Narcisse, MB',
    '52270': 'R.M. of St. Andrews incl. Selkirk Lockport and Ponemah, MB',
    '52310': 'R.M. of Portage la Prairie incl. St. Ambroise, MB',
    '52321': 'R.M. of St. François Xavier, MB',
    '52322': 'R.M. of Cartier incl. Elie St. Eustache and Springstein, MB',
    '52323': 'R.M. of Headingley, MB',
    '52331': 'R.M. of Grey incl. St. Claude Elm Creek and Fannystelle, MB',
    '52332': 'R.M. of Dufferin incl. Carman Roseisle and Homewood, MB',
    '52340': 'R.M. of Macdonald incl. Brunkild Starbuck and La Salle, MB',
    '52410': 'R.M. of St. Clements incl. Grand Beach Brokenhead and Libau, MB',
    '52422': 'R.M. of Brokenhead incl. Beausejour and Garson, MB',
    '52431': 'R.M. of Springfield incl. Anola and Birds Hill Prov. Park, MB',
    '52433': 'R.M. of East St. Paul incl. Birds Hill, MB',
    '52510': 'R.M. of Morris incl. Rosenort and Aubigny, MB',
    '52520': 'R.M. of Thompson incl. Miami Rosebank and Deerwood, MB',
    '52530': 'R.M. of Roland incl. Jordan and Myrtle, MB',
    '52540': 'R.M. of Montcalm incl. St. Jean Baptiste, MB',
    '52550': 'Mun. of Rhineland incl. Altona Plum Coulee and Gretna, MB',
    '52560': 'R.M. of Stanley incl. Winkler and Morden, MB',
    '52611': 'R.M. of Ritchot incl. St. Adolphe and Ste. Agathe, MB',
    '52612': 'R.M. of Tache incl. Lorette Ste-Geneviève and Landmark, MB',
    '52620': 'R.M. of De Salaberry incl. St-Pierre-Jolys and St. Malo, MB',
    '52630': 'R.M. of Hanover incl. Steinbach Niverville and Grunthal, MB',
    '52641': 'R.M. of Ste. Anne incl. Richer, MB',
    '52642': 'R.M. of La Broquerie incl. Marchand, MB',
    '52651': 'Mun. of Emerson-Franklin incl. Roseau River, MB',
    '52652': 'R.M. of Stuartburn incl. Zhoda Vita and Sundown, MB',
    '53110': 'Manigotagan Black River Res. and Hollow Water Res., MB',
    '53120': 'Bissett, MB',
    '53130': 'Nopiming Prov. Park, MB',
    '53140': 'R.M. of Alexander incl. Powerview-Pine Falls, MB',
    '53150': 'R.M. of Victoria Beach, MB',
    '53211': 'R.M. of Lac Du Bonnet, MB',
    '53221': 'L.G. of Pinawa incl. Seven Sisters Falls, MB',
    '53222': 'R.M. of Whitemouth incl. Elma, MB',
    '53231': 'Pointe du Bois, MB',
    '53232': 'Falcon Lake and West Hawk Lake, MB',
    '53243': 'Shoal Lake Reserves, MB',
    '53250': 'R.M. of Reynolds incl. Ste. Rita Hadashville and Rennie, MB',
    '53310': 'Buffalo Point Res. and Northwest Angle Prov. Forest, MB',
    '53320': 'R.M. of Piney incl. Sandilands and Sprague, MB',
    '54110': 'Grand Rapids and Easterville, MB',
    '54120': 'Waterhen Meadow Portage and Skownan, MB',
    '54210': 'R.M. of Grahamdale incl. Gypsumville Moosehorn and Camper, MB',
    '54221': 'Jackhead Res., MB',
    '54230': 'R.M. of West Interlake incl. Eriksdale and Ashern, MB',
    '54242': 'Mun. of Bifrost-Riverton incl. Arborg Hnausa and Hecla, MB',
    '54243': 'Moose Creek Prov. Forest Pine Dock and Matheson Island, MB',
    '54250': 'R.M. of Fisher incl. Poplarfield, MB',
    '54260': 'Peguis Res. and Fisher River Res., MB',
    '55110': 'Mun. of Roblin incl. Makaroff Shortdale and Bield, MB',
    '55121': 'R.M. of Dauphin incl. Sifton and Valley River, MB',
    '55122': 'Mun. of Ethelbert incl. Garland, MB',
    '55123': 'Gilbert Plains Mun. incl. Ashville, MB',
    '55131': 'Mossey River Mun. incl. Winnipegosis and Fork River, MB',
    '55132': 'Grandview Mun. incl. Valley River Res., MB',
    '55133': 'R.M. of Lakeshore incl. Ochre River and Makinak, MB',
    '55140': 'R.M. of Riding Mountain West incl. Asessippi Prov. Park, MB',
    '55150': 'Mun. of Russell-Binscarth incl. Gambler Res., MB',
    '55160': 'R.M. of Lakeshore incl. Rorketon and Toutes Aides, MB',
    '55210': 'Mun. of Harrison Park incl. Onanole Sandy Lake and Newdale, MB',
    '55221': 'Rossburn Mun. incl. Waywayseecappo Res., MB',
    '55222': 'Riding Mountain Nat. Park, MB',
    '55230': 'R.M. of Ellice-Archie incl. St-Lazare McAuley and Manson, MB',
    '55241': 'R.M. of Yellowhead incl. Shoal Lake and Elphinstone, MB',
    '55242': 'Prairie View Mun. incl. Birdtail Sioux Res., MB',
    '55243': 'Hamiota Mun. incl. McConnell and Lavinia, MB',
    '55251': 'R.M. of Oakview incl. Oak River and Rapid City, MB',
    '55252': 'R.M. of Minto-Odanah incl. Minnedosa and Moore Park, MB',
    '55253': 'Mun. of Clanwilliam-Erickson, MB',
    '55260': 'R.M. of Rosedale incl. Eden and Kelwood, MB',
    '55310': 'R.M. of Alonsa incl. Ebb and Flow Res. and Sandy Bay Res., MB',
    '55321': 'Mun. of Ste. Rose incl. Laurier, MB',
    '55331': 'Mun. of McCreary incl. Norgate, MB',
    '55340': 'Mun. of Glenella-Lansdowne incl. Arden and Tenby, MB',
    '55350': 'Mun. of WestLake-Gladstone incl. Plumas and Langruth, MB',
    '56110': 'The Pas Cormorant Westray and Wanless, MB',
    '56120': 'North and South Moose Lake incl. Moose Lake Res., MB',
    '56211': 'Westgate Red Deer Lake and Barrows, MB',
    '56212': 'Porcupine Prov. Forest, MB',
    '56221': 'R.M. of Mountain including Mafeking and Birch River, MB',
    '56222': 'Pelican Rapids and Shoal River First Nations, MB',
    '56231': 'Mun. of Swan Valley West incl. Benito, MB',
    '56232': 'Mun. of Minitonas-Bowsman incl. Renwer, MB',
    '56241': 'Duck Mountain Prov. Park and Prov. Forest, MB',
    '56242': 'R.M. of Mountain including Cowan and Camperville, MB',
    '57110': 'Molson Lake and Bear Lake, MB',
    '57120': 'Cross Lake and Jenpeg, MB',
    '57130': 'Wabowden, MB',
    '57140': 'Hwy 6 between Little Limestone Lake and Ponton, MB',
    '57150': 'Norway House, MB',
    '57200': 'Poplar River, MB',
    '57310': 'Berens River, MB',
    '57320': 'Little Grand Rapids and Atikaki Prov. Park, MB',
    '57330': 'Bloodvein, MB',
    '58100': 'Brochet, MB',
    '58200': 'Tadoule Lake, MB',
    '58310': 'Lynn Lake, MB',
    '58320': 'Leaf Rapids, MB',
    '58330': 'Pukatawagan, MB',
    '58410': 'South Indian Lake and Amisk Prov. Park, MB',
    '58420': 'Split Lake and York Landing, MB',
    '58430': 'Thompson Thicket Portage and Pikwitonei, MB',
    '58440': 'Nelson House, MB',
    '58510': 'Snow Lake and Herb Lake Landing, MB',
    '58520': 'Flin Flon Cranberry Portage and Grass River Prov. Park, MB',
    '59100': 'Churchill, MB',
    '59200': 'York, MB',
    '59300': 'Gillam, MB',
    '59400': 'Shamattawa, MB',
    '59510': 'Oxford House and Gods Lake, MB',
    '59520': 'Red Sucker Lake, MB',
    '59530': 'Island Lake, MB',
    '61111': 'R.M. of Deer Forks including Burstall and Estuary, SK',
    '61112': 'R.M. of Happyland including Leader Prelate and Mendham, SK',
    '61113': 'R.M. of Enterprise including Richmound, SK',
    '61114': 'R.M. of Fox Valley including Fox Valley, SK',
    '61115': 'R.M. of Big Stick including Golden Prairie, SK',
    '61121': 'R.M. of Clinworth including Sceptre Lemsford and Portreeve, SK',
    '61122': 'R.M. of Miry Creek including Abbey Lancer and Shackleton, SK',
    '61123': 'R.M. of Pittville including Hazlet, SK',
    '61131': 'R.M. of Piapot including Piapot, SK',
    '61132': 'R.M. of Gull Lake including Gull Lake and Tompkins, SK',
    '61133': 'R.M. of Carmichael including Carmichael, SK',
    '61211': 'R.M. of Lacadena including Kyle Tyner and Sanctuary, SK',
    '61212': 'R.M. of Victory including Beechy, SK',
    '61213': 'R.M. of Canaan including Lucky Lake, SK',
    '61221': 'R.M. of Riverside including Cabri Pennant and Success, SK',
    '61222': 'R.M. of Saskatchewan Landing including Stewart Valley, SK',
    '61223': 'R.M. of Webb including Webb and Antelope lake, SK',
    '61224': 'R.M. of Swift Current including Swift Current and Wymark, SK',
    '61225': 'R.M. of Lac Pelletier including Blumenhof, SK',
    '61231': 'R.M. of Excelsior including Waldeck Rush Lake and Main Centre, SK',
    '61232': 'R.M. of Morse including Herbert Morse Ernfold and Gouldtown, SK',
    '61233': 'R.M. of Coulee including Neidpath and McMahon, SK',
    '61234': 'R.M. of Lawtonia including Hodgeville, SK',
    '61235': 'R.M. of Glen Bain including Glen Bain, SK',
    '61236': 'R.M. of Whiska Creek including Vanguard Neville and Pambrun, SK',
    '61311': 'R.M. of Maple Creek including Maple Creek, SK',
    '61312': 'R.M. of Maple Creek including Cypress Hills Prov. Park, SK',
    '61313': 'R.M. of Reno including Consul Robsart and Willow Creek, SK',
    '61321': 'R.M. of Arlington including Dollard, SK',
    '61322': 'R.M. of White Valley including Eastend and Ravenscrag, SK',
    '61323': 'R.M. of Frontier including Frontier and Claydon, SK',
    '61331': 'R.M. of Bone Creek including Simmie and Scotsguard, SK',
    '61332': 'R.M. of Grassy Creek including Shaunavon, SK',
    '61333': 'R.M. of Wise Creek including Cadillac and Admiral, SK',
    '61341': 'R.M. of Lone Tree including Climax and Bracken, SK',
    '61342': 'R.M. of Val Marie including Val Marie Orkney and Monchy, SK',
    '61351': 'R.M. of Auvergne including Ponteix and Aneroid, SK',
    '61352': 'R.M. of Pinto Creek including Kincaid and Hazenmore, SK',
    '61353': 'R.M. of Glen McPherson west of Mankota, SK',
    '61354': 'R.M. of Mankota including Mankota and Ferland, SK',
    '62100': 'City of Regina, SK',
    '62211': 'R.M. of Maple Bush including Riverhurst and Douglas Prov. Park, SK',
    '62212': 'R.M. of Huron including Tugaske, SK',
    '62213': 'R.M. of Enfield including Central Butte, SK',
    '62214': 'R.M. of Eyebrow including Eyebrow and Brownlee, SK',
    '62221': 'R.M. of Craik including Craik and Aylesbury, SK',
    '62222': 'R.M. of Sarnia including Holdfast Chamberlain and Dilke, SK',
    '62223': 'R.M. of Marquis including Tuxford Keeler and Buffalo Pound, SK',
    '62224': 'R.M. of Dufferin including Bethune and Findlater, SK',
    '62231': 'R.M. of Chaplin including Chaplin, SK',
    '62232': 'R.M. of Wheatlands including Mortlach and Parkbeg, SK',
    '62233': 'R.M. of Shamrock including Shamrock and Kelstern, SK',
    '62234': 'R.M. of Rodgers including Coderre and Courval, SK',
    '62241': 'R.M. of Caron including Caronport and Caron, SK',
    '62242': 'R.M. of Moose Jaw including Pasqua and Bushell Park, SK',
    '62243': 'R.M. of Pense including Pense Belle Plaine and Stony Beach, SK',
    '62244': 'City of Moose Jaw, SK',
    '62245': 'R.M. of Hillsborough including Crestwynd and Old Wives lake, SK',
    '62246': 'R.M. of Redburn including Rouleau and Hearne, SK',
    '62247': 'R.M. of Baildon including Briercrest, SK',
    '62311': 'R.M. of McKillop including Strasbourg and Rowans Ravine Prov. Park, SK',
    '62312': 'R.M. of Longlaketon including Earl Grey and Silton, SK',
    '62313': 'R.M. of Lumsden including Lumsden Regina Beach and Craven, SK',
    '62321': 'R.M. of Cupar including Southey Cupar and Markinch, SK',
    '62322': 'R.M. of Lipton including Lipton and Dysart, SK',
    '62323': 'R.M. of Tullymet including Peepeekisis Res., SK',
    '62331': 'R.M. of Sherwood including Grand Coulee, SK',
    '62332': 'R.M. of Bratt\'s Lake including Wilcox Corinne and Estlin, SK',
    '62341': 'R.M. of Lajord including Lajord Kronau and Riceton, SK',
    '62342': 'R.M. of Francis including Vibank Sedley and Odessa, SK',
    '62343': 'R.M. of Montmartre including Assiniboine Res., SK',
    '62351': 'R.M. of Edenwold including Balgonie and Piapot Res., SK',
    '62352': 'R.M. of North Qu\'Appelle including Fort Qu\'Appelle, SK',
    '62353': 'R.M. of South Qu\'Appelle including Qu\'Appelle and Edgeley, SK',
    '62361': 'R.M. of Abernethy including Balcarres and Abernethy, SK',
    '62362': 'R.M. of Indian Head including Indian Head and Sintaluta, SK',
    '62411': 'R.M. of Gravelbourg including Gravelbourg and Bateman, SK',
    '62412': 'R.M. of Sutton including Mazenod Palmer and Vantage, SK',
    '62413': 'R.M. of Wood River including Lafleche Woodrow and Melaval, SK',
    '62414': 'R.M. of Stonehenge including Limerick and Congress, SK',
    '62421': 'R.M. of Waverley including Glentworth and Fir Mountain, SK',
    '62422': 'R.M. of Old Post including Wood Mountain and Killdeer, SK',
    '62431': 'R.M. of Lake Johnson including Mossbank and Ardill, SK',
    '62432': 'R.M. of Terrell including Spring Valley and Cardross, SK',
    '62433': 'R.M. of Lake of The Rivers including Assiniboia, SK',
    '62434': 'R.M. of Excel including Viceroy Ormiston and Verwood, SK',
    '62441': 'R.M. of Willow Bunch including Willow Bunch and St Victor, SK',
    '62442': 'R.M. of Poplar Valley including Rockglen and Fife Lake, SK',
    '62443': 'R.M. of Hart Butte including Coronach, SK',
    '62451': 'R.M. of Elmsthorpe including Avonlea and Truax, SK',
    '62452': 'R.M. of Key West including Ogema and Kayville, SK',
    '62461': 'R.M. of Bengough including Bengough, SK',
    '62462': 'R.M. of The Gap including Ceylon and Hardy, SK',
    '62463': 'R.M. of Happy Valley including Big Beaver, SK',
    '62464': 'R.M. of Surprise Valley including Minton and Regway, SK',
    '62511': 'R.M. of Caledonia including Milestone and Parry, SK',
    '62512': 'R.M. of Scott including Yellow Grass Lang and Lewvan, SK',
    '62513': 'R.M. of Norton including Pangman and Khedive, SK',
    '62514': 'R.M. of Brokenshell including Trossachs, SK',
    '62521': 'R.M. of Wellington including Cedoux Colfax and Tyvan, SK',
    '62522': 'R.M. of Fillmore including Fillmore Creelman and Osage, SK',
    '62523': 'R.M. of Weyburn including Weyburn and McTaggart, SK',
    '62524': 'R.M. of Griffin including Griffin and Froude, SK',
    '62531': 'R.M. of Laurier including Radville, SK',
    '62532': 'R.M. of Lomond including Colgate and Goodwater, SK',
    '62533': 'R.M. of Lake Alma including Lake Alma and Beaubier, SK',
    '62534': 'R.M. of Souris Valley including Tribune and Oungre, SK',
    '62541': 'R.M. of Cymri including Midale Macoun and Halbrite, SK',
    '62542': 'R.M. of Benson including Benson, SK',
    '62543': 'R.M. of Cambria including Torquay and Outram, SK',
    '62544': 'R.M. of Estevan including Estevan and Hitchcock, SK',
    '63111': 'R.M. of Garry including Jedburgh, SK',
    '63112': 'R.M. of Orkney including Yorkton Springside and Ebenezer, SK',
    '63113': 'R.M. of Stanley including Goodeve Fenwood and Duff, SK',
    '63114': 'R.M. of Cana including Melville, SK',
    '63121': 'R.M. of McLeod including Lemberg and Neudorf, SK',
    '63122': 'R.M. of Grayson including Grayson Dubuc and Killaly, SK',
    '63131': 'R.M. of Wallace including Rhein Stornoway Tonkin and Rokeby, SK',
    '63132': 'R.M. of Calder including Calder and Wroxton, SK',
    '63133': 'R.M. of Saltcoats including Saltcoats and Bredenbury, SK',
    '63134': 'R.M. of Churchbridge including Churchbridge and MacNutt, SK',
    '63141': 'R.M. of Fertile Belt including Esterhazy Stockholm and Bangor, SK',
    '63142': 'R.M. of Langenburg including Langenburg Yarbo and Marchwell, SK',
    '63143': 'R.M. of Spy Hill including Spy Hill Gerald and Tantallon, SK',
    '63211': 'R.M. of Wolseley including Wolseley and Summerberry, SK',
    '63212': 'R.M. of Elcapo including Broadview and Cowessess Res., SK',
    '63221': 'R.M. of Chester including Windthorst Glenavon and Peebles, SK',
    '63222': 'R.M. of Hazelwood south of Kipling, SK',
    '63223': 'R.M. of Golden West including Ocean Man Res. and Handsworth, SK',
    '63224': 'R.M. of Kingsley including Kipling, SK',
    '63231': 'R.M. of Silverwood south of Whitewood, SK',
    '63232': 'R.M. of Wawken including Wawota Kennedy and Kenosee Lake, SK',
    '63241': 'R.M. of Martin including Wapella and Red Jacket, SK',
    '63242': 'R.M. of Moosomin including Moosomin Welwyn and Fleming, SK',
    '63243': 'R.M. of Walpole including Kelso, SK',
    '63244': 'R.M. of Maryfield including Maryfield and Fairlight, SK',
    '63251': 'R.M. of Willowdale including Whitewood and Ochapowace Res., SK',
    '63252': 'R.M. of Rocanville including Rocanville, SK',
    '63311': 'R.M. of Tecumseh including Stoughton Forget and Heward, SK',
    '63312': 'R.M. of Brock including Arcola and Kisbey, SK',
    '63321': 'R.M. of Browning including Lampman, SK',
    '63322': 'R.M. of Coalfields including Bienfait and North Portal, SK',
    '63331': 'R.M. of Moose Creek including Alameda, SK',
    '63332': 'R.M. of Enniskillen including Oxbow and Northgate, SK',
    '63341': 'R.M. of Moose Mountain including Carlyle and Manor, SK',
    '63342': 'R.M. of Antler including Redvers Antler and Wauchope, SK',
    '63351': 'R.M. of Storthoaks including Storthoaks and Fertile, SK',
    '63352': 'R.M. of Reciprocity including Alida, SK',
    '63353': 'R.M. of Mount Pleasant including Carnduff, SK',
    '63354': 'R.M. of Argyle including Gainsborough and Carievale, SK',
    '64110': 'R.M. of Hudson Bay including Shoal Lake and Red Earth Reserves, SK',
    '64120': 'R.M. of Hudson Bay including Hudson Bay and Reserve, SK',
    '64130': 'R.M. of Porcupine including Porcupine Plain and Weekes, SK',
    '64211': 'R.M. of Hazel Dell including Lintlaw and Hazel Dell, SK',
    '64212': 'R.M. of Preeceville including Preeceville and Sturgis, SK',
    '64213': 'R.M. of Invermay including Invermay and Rama, SK',
    '64214': 'R.M. of Buchanan including Buchanan Amsterdam and Tadmore, SK',
    '64221': 'R.M. of Insinger including Theodore and Sheho, SK',
    '64222': 'R.M. of Good Lake including Canora and Good Spirit Lake Prov. Park, SK',
    '64231': 'R.M. of Keys including The Key Res., SK',
    '64232': 'R.M. of St Philips including Pelly and St Philips, SK',
    '64233': 'R.M. of Sliding Hills including Veregin Mikado and Hamton, SK',
    '64234': 'R.M. of Cote including Kamsack Togo and Duck Mountain Prov. Park, SK',
    '64241': 'R.M. of Clayton including Norquay Stenen and Swan Plain, SK',
    '64242': 'R.M. of Livingston including Arran, SK',
    '65100': 'City of Saskatoon, SK',
    '65211': 'R.M. of Spiritwood including Spiritwood and Leoville, SK',
    '65212': 'R.M. of Canwood including Debden and Big River Res., SK',
    '65221': 'R.M. of Meeting Lake, SK',
    '65222': 'R.M. of Leask including Leask Mistawasis Res. and Parkside, SK',
    '65230': 'R.M. of Shellbrook including Sturgeon Lake Res., SK',
    '65240': 'R.M. of Duck Lake including Duck Lake and Beardy\'s Res., SK',
    '65251': 'District of Lakeland including Emma Lake and Anglin Lake, SK',
    '65252': 'R.M. of Paddockwood including Candle Lake and Paddockwood, SK',
    '65261': 'R.M. of Buckland including Wahpeton Res. and Spruce Home, SK',
    '65262': 'R.M. of Garden River including Meath Park and Albertville, SK',
    '65263': 'City of Prince Albert, SK',
    '65271': 'R.M. of Prince Albert including Davis, SK',
    '65272': 'R.M. of Birch Hills including Muskoday Res., SK',
    '65273': 'R.M. of St Louis including One Arrow Res. and Domremy, SK',
    '65310': 'R.M. of Torch River including Choiceland and White Fox, SK',
    '65321': 'R.M. of Nipawin including Nipawin Aylsham and Pontrilas, SK',
    '65322': 'R.M. of Moose Range including Carrot River and Tobin Lake, SK',
    '65331': 'R.M. of Kinistino including Kinistino and James Smith Res., SK',
    '65332': 'R.M. of Invergordon including Yellow Creek and Tarnopol, SK',
    '65333': 'R.M. of Flett\'s Springs including Beatty Ethelton and Pathlow, SK',
    '65334': 'R.M. of Three Lakes including Middle Lake and St Benedict, SK',
    '65335': 'R.M. of Lake Lenore including St. Brieux, SK',
    '65341': 'R.M. of Willow Creek including Gronlid and Fairy Glen, SK',
    '65342': 'R.M. of Connaught including Ridgedale and New Osgoode, SK',
    '65343': 'R.M. of Star City including Melfort and Star City, SK',
    '65344': 'R.M. of Tisdale including Tisdale Eldersley and Sylvania, SK',
    '65345': 'R.M. of Pleasantdale including Naicam and Pleasantdale, SK',
    '65346': 'R.M. of Barrier Valley including Archerwill and McKague, SK',
    '65351': 'R.M. of Arborfield including Arborfield and Zenon Park, SK',
    '65352': 'R.M. of Bjorkdale including Greenwater Lake Prov. Park, SK',
    '65411': 'R.M. of Redberry including Hafford and Krydor, SK',
    '65412': 'R.M. of Blaine Lake including Blaine Lake, SK',
    '65413': 'R.M. of Great Bend including Radisson and Borden, SK',
    '65421': 'R.M. of Laird including Waldheim Hepburn and Laird, SK',
    '65422': 'R.M. of Rosthern including Rosthern Hague and Carlton, SK',
    '65431': 'R.M. of Eagle Creek including Arelee and Sonningdale, SK',
    '65432': 'R.M. of Corman Park including Martensville Warman and Langham, SK',
    '65433': 'R.M. of Perdue including Perdue and Kinley, SK',
    '65434': 'R.M. of Vanscoy including Delisle Asquith and Vanscoy, SK',
    '65441': 'R.M. of Aberdeen including Aberdeen, SK',
    '65442': 'R.M. of Fish Creek including Alvena, SK',
    '65443': 'R.M. of Hoodoo including Wakaw and Cudworth, SK',
    '65444': 'R.M. of Grant including Vonda Prud\'homme and Smuts, SK',
    '65445': 'R.M. of Bayne including Bruno Peterson and Dana, SK',
    '65451': 'R.M. of Colonsay including Colonsay and Meacham, SK',
    '65452': 'R.M. of Viscount including Viscount and Plunkett, SK',
    '65453': 'R.M. of Blucher including Allan Clavet Bradwell and Elstow, SK',
    '65511': 'R.M. of Harris including Harris and Tessier, SK',
    '65512': 'R.M. of Montrose including Donovan and Swanson, SK',
    '65513': 'R.M. of Milden including Dinsmore Milden and Wiseton, SK',
    '65514': 'R.M. of Fertile Valley including Conquest Macrorie and Bounty, SK',
    '65515': 'R.M. of King George northwest of Lucky Lake, SK',
    '65516': 'R.M. of Coteau including Birsay and Danielson Prov. Park, SK',
    '65521': 'R.M. of Dundurn including Dundurn and Blackstrap Prov. Park, SK',
    '65522': 'R.M. of Rudy including Outlook and Glenside, SK',
    '65523': 'R.M. of Rosedale including Hanley, SK',
    '65524': 'R.M. of Loreburn including Elbow Loreburn and Hawarden, SK',
    '65531': 'R.M. of Lost River including South Allan and the Allan Hills, SK',
    '65532': 'R.M. of Morris including Watrous Young and Zelma, SK',
    '65533': 'R.M. of McCraney including Kenaston and Bladworth, SK',
    '65534': 'R.M. of Wood Creek including Simpson, SK',
    '65541': 'R.M. of Arm River including Davidson and Girvin, SK',
    '65542': 'R.M. of Willner west of Davidson, SK',
    '65543': 'R.M. of Big Arm including Imperial and Liberty, SK',
    '65611': 'R.M. of Humboldt including Humboldt Carmel and Fulda, SK',
    '65612': 'R.M. of St Peter including Muenster and Lake Lenore, SK',
    '65613': 'R.M. of Wolverine including Burr, SK',
    '65614': 'R.M. of Leroy including Leroy, SK',
    '65621': 'R.M. of Spalding including Spalding, SK',
    '65622': 'R.M. of Ponass Lake including Rose Valley Fosston and Nora, SK',
    '65623': 'R.M. of Lakeside including Watson and Quill Lake, SK',
    '65624': 'R.M. of Lakeview including Wadena and Clair, SK',
    '65631': 'R.M. of Usborne including Lanigan Drake and Guernsey, SK',
    '65632': 'R.M. of Prairie Rose including Jansen and Esk, SK',
    '65633': 'R.M. of Wreford including Nokomis and Venn, SK',
    '65634': 'R.M. of Mount Hope including Semans, SK',
    '65635': 'R.M. of Last Mountain Valley including Govan and Duval, SK',
    '65641': 'R.M. of Big Quill including Wynyard Dafoe and Kandahar, SK',
    '65642': 'R.M. of Elfros including Elfros Leslie and Mozart, SK',
    '65643': 'R.M. of Kutawa including Raymore Punnichy and Poorman Res., SK',
    '65644': 'R.M. of Emerald including Wishart and Bankend, SK',
    '65645': 'R.M. of Touchwood including Serath and Touchwood Hills Prov. Park, SK',
    '65646': 'R.M. of Kellross including Kelliher and Lestock, SK',
    '65651': 'R.M. of Kelvington including Yellowquill Res., SK',
    '65652': 'R.M. of Sasman including Margo Kylemore and Nut Mountain, SK',
    '65653': 'R.M. of Foam Lake including Foam Lake and Fishing Lake Res., SK',
    '65654': 'R.M. of Ituna Bon Accord including Ituna and Hubbard, SK',
    '66110': 'R.M. of Meadow Lake including Waterhen Res., SK',
    '66120': 'R.M. of Beaver River including Pierceland and Goodsoil, SK',
    '66130': 'Green Lake, SK',
    '66140': 'R.M. of Loon Lake including Loon Lake and Makwa, SK',
    '66150': 'R.M. of Big River including Big River and Chitek Lake, SK',
    '66211': 'R.M. of Frenchman Butte including St. Walburg, SK',
    '66212': 'R.M. of Mervin including Turtleford Mervin and Spruce Lake, SK',
    '66213': 'R.M. of Turtle River including Edam and Vawn, SK',
    '66221': 'R.M. of Britannia including Hillmond, SK',
    '66222': 'R.M. of Wilton including Lashburn Marshall and Lone Rock, SK',
    '66223': 'R.M. of Eldon including Maidstone and Waseca, SK',
    '66224': 'R.M. of Paynton including Paynton, SK',
    '66231': 'R.M. of Manitou Lake including Marsden, SK',
    '66232': 'R.M. of Hillsdale including Neilburg and Baldwinton, SK',
    '66233': 'R.M. of Senlac including Senlac, SK',
    '66234': 'R.M. of Round Valley including Unity, SK',
    '66241': 'R.M. of Cut Knife including Cut Knife, SK',
    '66242': 'R.M. of Battle River including Sweet Grass Res. and Delmas, SK',
    '66243': 'R.M. of Buffalo including Wilkie and Phippen, SK',
    '66251': 'R.M. of Parkdale including Glaslyn and Fairholme, SK',
    '66252': 'R.M. of Medstead including Medstead Belbutte and Birch Lake, SK',
    '66253': 'R.M. of Meota including Meota and The Battlefords Prov. Park, SK',
    '66254': 'R.M. of Round Hill including Rabbit Lake and Whitkow, SK',
    '66260': 'The Battlefords, SK',
    '66271': 'R.M. of North Battleford northwest of The Battlefords, SK',
    '66272': 'R.M. of Douglas including Speers Richard and Alticane, SK',
    '66273': 'R.M. of Mayfield including Maymont Denholm and Fielding, SK',
    '66280': 'R.M. of Glenside north of Biggar, SK',
    '66311': 'R.M. of Eye Hill including Macklin Denzil and Evesham, SK',
    '66312': 'R.M. of Grass Lake including Salvador and Reward, SK',
    '66313': 'R.M. of Heart\'s Hill including Cactus Lake, SK',
    '66314': 'R.M. of Progress including Kerrobert and Luseland, SK',
    '66321': 'R.M. of Tramping Lake including Scott and Revenue, SK',
    '66322': 'R.M. of Reford including Landis and Leipzig, SK',
    '66323': 'R.M. of Mariposa including Tramping Lake and Broadacres, SK',
    '66324': 'R.M. of Grandview including Handel and Kelfield, SK',
    '66331': 'R.M. of Rosemount including Cando and Traynor, SK',
    '66332': 'R.M. of Biggar including Biggar and Springwater, SK',
    '66341': 'R.M. of Antelope Park including Loverna and Hoosier, SK',
    '66342': 'R.M. of Prairiedale including Major and Smiley, SK',
    '66343': 'R.M. of Milton including Alsask and Marengo, SK',
    '66351': 'R.M. of Oakdale including Coleville, SK',
    '66352': 'R.M. of Winslow including Dodsland and Plenty, SK',
    '66353': 'R.M. of Kindersley including Kindersley Brock and Flaxcombe, SK',
    '66361': 'R.M. of Mountain View including Herschel and Stranraer, SK',
    '66362': 'R.M. of Marriott south of Biggar, SK',
    '66363': 'R.M. of Pleasant Valley including McGee and Fiske, SK',
    '66364': 'R.M. of St Andrews including Rosetown and Zealandia, SK',
    '66371': 'R.M. of Chesterfield including Eatonia and Mantario, SK',
    '66372': 'R.M. of Newcombe including Glidden and Madison, SK',
    '66381': 'R.M. of Monet including Elrose Wartime and Forgan, SK',
    '66382': 'R.M. of Snipe Lake including Eston and Plato, SK',
    '66400': 'City of Lloydminster, SK,AB',
    '67110': 'Buffalo Narrows and Peter Pond Lake, SK',
    '67120': 'Île à la Crosse and Beauval, SK',
    '67210': 'Hwy 165 between hwys 2 and 914 including Pinehouse Lake, SK',
    '67220': 'Lac la Ronge Prov. Park including La Ronge, SK',
    '67230': 'Candle Lake Prov. Park and Narrow Hills Prov. Park, SK',
    '67240': 'Montreal Lake and Molanosa, SK',
    '67250': 'Prince Albert Nat. Park, SK',
    '67310': 'Hwy 135 including Pelican Narrows and Sandy Bay, SK',
    '67320': 'Seabee Mine, SK',
    '67330': 'Hanson Lake Road east of Hwy 135 including Creighton, SK',
    '67340': 'Hanson Lake Road between Hwys 165 and 135, SK',
    '67350': 'Cumberland House, SK',
    '68100': 'Uranium City - Camsell Portage, SK',
    '68210': 'Fond-du-Lac, SK',
    '68220': 'Stony Rapids and Black Lake, SK',
    '68310': 'Cluff Lake Mine, SK',
    '68320': 'La Loche and Clearwater River Prov. Park, SK',
    '68400': 'Cree Lake - Key Lake, SK',
    '68500': 'Wollaston Lake - Collins Bay, SK',
    '68600': 'Southend - Brabant Lake - Kinoosao, SK',
    '71110': 'Jasper Nat. Park near Pocahontas, AB',
    '71120': 'Jasper Nat. Park near Jasper, AB',
    '71130': 'Jasper Nat. Park near and south of Sunwapta Falls, AB',
    '71210': 'Yellowhead Co. near Cadomin and Robb, AB',
    '71220': 'Clearwater Co. near Chungo Creek, AB',
    '71230': 'Clearwater Co. near Nordegg and Big Horn Res., AB',
    '71240': 'Clearwater Co. near Ya-Ha-Tinda Ranch, AB',
    '71310': 'Brazeau Co. near Cynthia and Lodgepole, AB',
    '71320': 'Yellowhead Co. near Minnow and Wolf Lakes and Elk River, AB',
    '71330': 'O\'Chiese 203 Res. and Clearwater Co. near Sunchild Cree Res., AB',
    '71340': 'Brazeau Co. near Brazeau Dam, AB',
    '71350': 'Clearwater Co. near Rocky Mtn House and Crimson Lake, AB',
    '71360': 'Clearwater Co. near Caroline and James River Bridge, AB',
    '71410': 'Clearwater Co. near Siffleur Wilderness Area, AB',
    '71420': 'Banff Nat. Park near Saskatchewan River Crossing, AB',
    '71430': 'Banff Nat. Park near Lake Louise, AB',
    '71440': 'Banff Nat. Park near Banff, AB',
    '71510': 'M.D. of Bighorn near Ghost River Wilderness, AB',
    '71520': 'M.D. of Bighorn near Canmore Exshaw and Ghost Lake, AB',
    '71530': 'Kananaskis Improvement District near Kananaskis Village, AB',
    '71540': 'Kananaskis Improvement District near Highwood House, AB',
    '72111': 'Lacombe Co. near Eckville, AB',
    '72112': 'Lacombe Co. near Lacombe Blackfalds and Bentley, AB',
    '72113': 'Lacombe Co. near Clive Alix and Mirror, AB',
    '72121': 'Red Deer Co. near Sylvan Lake and Stephansson House, AB',
    '72122': 'Red Deer Co. near Spruce View and Red Lodge Prov. Park, AB',
    '72123': 'Red Deer Co. near Penhold Innisfail and Bowden, AB',
    '72124': 'Red Deer Co. near Pine Lake, AB',
    '72125': 'Red Deer Co. near Elnora Lousana and Delburne, AB',
    '72131': 'Co. of Stettler near Stettler Nevis and Rochon Sands, AB',
    '72132': 'Co. of Stettler near Big Valley, AB',
    '72133': 'Co. of Stettler near Donalda, AB',
    '72134': 'Co. of Stettler near Botha and Gadsby, AB',
    '72135': 'Co. of Stettler near Byemoor and Endiang, AB',
    '72140': 'City of Red Deer, AB',
    '72150': 'Co. of Paintearth near Halkirk and Big Knife Prov. Park, AB',
    '72160': 'Flagstaff Co. near Forestburg and Galahad, AB',
    '72170': 'Camrose Co. near Bashaw and Meeting Creek, AB',
    '72180': 'Ponoka Co. near Ponoka and Maskwacis, AB',
    '72210': 'Mountain View Co. near Sundre, AB',
    '72220': 'Mountain View Co. near Olds and Didsbury, AB',
    '72230': 'Mountain View Co. near Cremona and Water Valley, AB',
    '72240': 'Mountain View Co. near Carstairs and Stirlingville, AB',
    '72250': 'Rocky View Co. near Airdrie and Crossfield, AB',
    '72260': 'Rocky View Co. near Bottrel and Madden, AB',
    '72270': 'Rocky View Co. near Cochrane, AB',
    '72311': 'Kneehill Co. near Torrington and Wimborne, AB',
    '72312': 'Kneehill Co. near Trochu and Huxley, AB',
    '72313': 'Kneehill Co. near Three Hills, AB',
    '72321': 'Kneehill Co. near Acme and Linden, AB',
    '72322': 'Kneehill Co. near Carbon, AB',
    '72331': 'Starland Co. near Rumsey and Rowley, AB',
    '72332': 'Starland Co. near Morrin and Munson, AB',
    '72333': 'Starland Co. near Michichi and Delia, AB',
    '72341': 'Wheatland Co. near Rockyford and Rosebud, AB',
    '72342': 'Wheatland Co. near Hwys 569 and 848, AB',
    '72350': 'Town of Drumheller, AB',
    '72360': 'Rocky View Co. near Irricana Beiseker and Kathyrn, AB',
    '72370': 'S.A. 2 near Finnegan and Little Fish Lake Prov. Park, AB',
    '72400': 'City of Calgary, AB',
    '72510': 'Rocky View Co. near Bragg Creek and Tsuu T\'ina Res., AB',
    '72521': 'Foothills Co. near Priddis and Brown-Lowery Prov. Park, AB',
    '72522': 'Foothills Co. near Diamond Valley, AB',
    '72523': 'Foothills Co. near Longview and Eden Valley Res., AB',
    '72531': 'Foothills Co. near Okotoks and De Winton, AB',
    '72532': 'Foothills Co. near High River and Aldersyde, AB',
    '72533': 'Foothills Co. near Cayley, AB',
    '72541': 'M.D. of Willow Creek near Nanton and Parkland, AB',
    '72542': 'M.D. of Willow Creek near Claresholm and Stavely, AB',
    '72610': 'Rocky View Co. near Chestermere Dalroy and Dalemead, AB',
    '72620': 'Foothills Co. near Blackie, AB',
    '72631': 'Wheatland Co. near Strathmore Lyalta and Carseland, AB',
    '72632': 'Wheatland Co. near Standard and Gleichen, AB',
    '72633': 'Siksika Res. 146, AB',
    '72634': 'Wheatland Co. near Hussar, AB',
    '72641': 'Vulcan Co. near Arrowwood Herronton and Queenstown, AB',
    '72642': 'Vulcan Co. near Vulcan and Ensign, AB',
    '72643': 'Vulcan Co. near Carmangay and Champion, AB',
    '72644': 'Vulcan Co. near Lomond Travers and Little Bow Reservoirs, AB',
    '72645': 'Vulcan Co. near Milo, AB',
    '72651': 'Co. of Newell near Bassano, AB',
    '72652': 'Co. of Newell near Gem, AB',
    '72653': 'Co. of Newell near Brooks Rosemary and Duchess, AB',
    '72654': 'Co. of Newell near Scandia and Kinbrook Island Prov. Park, AB',
    '72660': 'M.D. of Taber near Enchant, AB',
    '73110': 'M.D. of Ranchland, AB',
    '73120': 'M.D. of Pincher Creek near Cowley Burmis and Maycroft, AB',
    '73130': 'Piikani Reserve, AB',
    '73140': 'Municipality of Crowsnest Pass including Coleman and Frank, AB',
    '73150': 'M.D. of Pincher Creek near Beauvais Lake Prov. Park, AB',
    '73160': 'M.D. of Pincher Creek near Pincher Creek and Twin Butte, AB',
    '73170': 'Waterton Lakes Nat. Park and Blood Res. 148A, AB',
    '73211': 'M.D. of Willow Creek near Granum and Peigan Timber Limit, AB',
    '73212': 'M.D. of Willow Creek near Fort Macleod, AB',
    '73221': 'Blood Res. 148 including Stand Off, AB',
    '73222': 'Cardston Co. near Hill Spring and Glenwood, AB',
    '73231': 'Cardston Co. near Magrath and Woolford Prov. Park, AB',
    '73232': 'Cardston Co. near Del Bonita and Kimball, AB',
    '73241': 'Cardston Co. near Mountain View and Beazer, AB',
    '73242': 'Cardston Co. near Cardston and Carway, AB',
    '73311': 'Co. of Lethbridge near Coalhurst Nobleford and Barons, AB',
    '73312': 'Co. of Lethbridge near Picture Butte and Turin, AB',
    '73313': 'Co. of Lethbridge near Coaldale, AB',
    '73314': 'City of Lethbridge, AB',
    '73321': 'M.D. of Taber near Vauxhall and Hays, AB',
    '73322': 'M.D. of Taber near Taber and Barnwell, AB',
    '73323': 'M.D. of Taber near Grassy Lake and Hwys 877 and 513, AB',
    '73331': 'Co. of Warner near Raymond Stirling and New Dayton, AB',
    '73332': 'Co. of Warner near Wrentham, AB',
    '73341': 'Co. of Warner near Warner, AB',
    '73342': 'Co. of Warner near Milk River and Coutts, AB',
    '73343': 'Co. of Warner near Writing-On-Stone Prov. Park, AB',
    '73350': 'Co. of Forty Mile near Skiff, AB',
    '74111': 'Co. of Paintearth near Castor and Fleet, AB',
    '74112': 'Co. of Paintearth near Brownfield, AB',
    '74113': 'Co. of Paintearth near Coronation and Throne, AB',
    '74121': 'S.A. 2 near Spondin and Scapa, AB',
    '74122': 'S.A. 2 near Hanna and Richdale, AB',
    '74123': 'S.A. 2 near Sunnynook, AB',
    '74124': 'S.A. 2 near Cessford Wardlow and Pollockville, AB',
    '74131': 'S.A. 4 near Veteran and Consort, AB',
    '74132': 'S.A. 4 near Hemaruka Wiste and Monitor Creek, AB',
    '74133': 'S.A. 4 near Kirriemuir and Compeer, AB',
    '74141': 'S.A. 3 near Youngstown, AB',
    '74142': 'S.A. 3 near Big Stone Cappon and Gold Spur, AB',
    '74143': 'S.A. 3 near Sedalia and New Brigden, AB',
    '74144': 'S.A. 3 near Oyen and Cereal, AB',
    '74145': 'S.A. 3 near Sibbald and Esther, AB',
    '74150': 'M.D. of Provost near Bodo, AB',
    '74160': 'M.D. of Acadia including Acadia Valley, AB',
    '74211': 'Cypress Co. near Tide Lake, AB',
    '74212': 'Cypress Co. near Suffield and Hwy 879, AB',
    '74221': 'S.A. 2 near Iddesleigh and Dinosaur Prov. Park, AB',
    '74222': 'S.A. 2 near Jenner and Atlee, AB',
    '74223': 'S.A. 2 near Buffalo and Cavendish, AB',
    '74224': 'S.A. 2 near Bindloss Empress and Social Plains, AB',
    '74231': 'Co. of Newell near Patricia, AB',
    '74232': 'Co. of Newell near Tilley and Rolling Hills, AB',
    '74241': 'Cypress Co. near CFB Suffield, AB',
    '74242': 'Cypress Co. near Bowell and Redcliff, AB',
    '74251': 'Cypress Co. near Seven Persons, AB',
    '74252': 'Cypress Co. near Dunmore and Woolchester, AB',
    '74253': 'Cypress Co. near Irvine and Walsh, AB',
    '74261': 'Cypress Co. near Bowmanton Schuler and Hilda, AB',
    '74262': 'Cypress Co. near McNeill and Sandy Point District Park, AB',
    '74270': 'City of Medicine Hat, AB',
    '74280': 'Co. of Forty Mile near Bow Island and Whitla, AB',
    '74310': 'Co. of Forty Mile near Foremost, AB',
    '74320': 'Co. of Forty Mile near Etzikom and Maleb, AB',
    '74330': 'Co. of Forty Mile near Orion and Manyberries, AB',
    '74340': 'Cypress Co. near Cypress Hills Prov. Park and Cressday, AB',
    '74350': 'Co. of Forty Mile near Aden and Kennedy Coulee, AB',
    '74360': 'Cypress Co. near Onefour and Wild Horse, AB',
    '75111': 'Lac La Biche Co. near Plamondon Hylo and Avenir, AB',
    '75112': 'Lac La Biche Co. near Heart Lake, AB',
    '75113': 'Lac La Biche Co. near Lac La Biche and Square Lake, AB',
    '75114': 'Lac La Biche Co. near Lakeland Prov. Park and Rec. Area, AB',
    '75115': 'Lac La Biche Co. near Fork Lake, AB',
    '75116': 'Improvement District 349 including Cold Lake Air Weapons Range, AB',
    '75121': 'Smoky Lake Co. near Buffalo Lake and Kikino Smts, AB',
    '75122': 'Smoky Lake Co. near Vilna Saddle Lake and Whitefish Lake, AB',
    '75131': 'Co. of St. Paul near Ashmont St. Vincent and St. Lina, AB',
    '75132': 'Co. of St. Paul near St. Paul and Lafond, AB',
    '75133': 'Co. of St. Paul near Elk Point and St. Edouard, AB',
    '75134': 'Co. of St. Paul near Lindbergh and Frog Lake, AB',
    '75141': 'M.D. of Bonnyville near La Corey Wolf Lake and Truman, AB',
    '75142': 'M.D. of Bonnyville near Glendon and Moose Lake, AB',
    '75143': 'M.D. of Bonnyville near Bonnyville Ardmore and Kehewin Res., AB',
    '75144': 'M.D. of Bonnyville near Cold Lake and City of Cold Lake, AB',
    '75145': 'M.D. of Bonnyville near Beaverdam, AB',
    '75146': 'M.D. of Bonnyville near Fishing Lake Smt, AB',
    '75211': 'Co. of Two Hills near Two Hills and Brosseau, AB',
    '75212': 'Co. of Two Hills near Myrnam and Derwent, AB',
    '75221': 'Co. of Minburn near Innisfree Lavoy and Ranfurly, AB',
    '75222': 'Co. of Minburn near Minburn and Mannville, AB',
    '75230': 'Beaver Co. near Viking and Kinsella, AB',
    '75241': 'Flagstaff Co. near Killam and Sedgewick, AB',
    '75242': 'Flagstaff Co. near Lougheed and Hardisty, AB',
    '75243': 'Flagstaff Co. near Alliance and Bellshill Lake, AB',
    '75251': 'Co. of Vermilion River near Vermilion, AB',
    '75252': 'Co. of Vermilion River near Islay and McNabb Sanctuary, AB',
    '75253': 'Co. of Vermilion River near Dewberry and Clandonald, AB',
    '75254': 'Co. of Vermilion River near Tulliby Lake, AB',
    '75255': 'Co. of Vermilion River near Kitscoty and Marwayne, AB',
    '75256': 'Co. of Vermilion River near Paradise Valley, AB',
    '75260': 'City of Lloydminster, SK,AB',
    '75271': 'M.D. of Wainwright near Irma, AB',
    '75272': 'M.D. of Wainwright near Wainwright, AB',
    '75273': 'M.D. of Wainwright near Edgerton and Koroluk Landslide, AB',
    '75274': 'M.D. of Wainwright near Chauvin Dillberry Lake and Roros, AB',
    '75281': 'M.D. of Provost near Hughenden Amisk and Kessler, AB',
    '75282': 'M.D. of Provost near Czar Metiskow and Cadogan, AB',
    '75283': 'M.D. of Provost near Provost and Hayter, AB',
    '76110': 'Woodlands Co. near Fort Assiniboine Timeu and Topland, AB',
    '76121': 'Co. of Barrhead near Thunder Lake and Holmes Crossing, AB',
    '76122': 'Co. of Barrhead near Neerlandia Bloomsbury and Vega, AB',
    '76123': 'Co. of Barrhead near Barrhead and Lac la Nonne, AB',
    '76130': 'M.D. of Lesser Slave River near Chisholm and Cross Lake, AB',
    '76141': 'Westlock Co. near Larkspur Fawcett and Jarvie, AB',
    '76142': 'Westlock Co. near Westlock and Clyde, AB',
    '76151': 'Athabasca Co. near Athabasca and Island Lake, AB',
    '76152': 'Athabasca Co. near Rochester Colinton and Meanook, AB',
    '76153': 'Athabasca Co. near Grassland and Atmore, AB',
    '76154': 'Athabasca Co. near Boyle and Caslan, AB',
    '76160': 'Thorhild Co. near Newbrook and Long Lake Prov. Park, AB',
    '76210': 'Yellowhead Co. near MacKay Wildwood and Evansburg, AB',
    '76221': 'Lac Ste. Anne Co. near Mayerthorpe and Sangudo, AB',
    '76222': 'Lac Ste. Anne Co. near Cherhill and Glenevis, AB',
    '76223': 'Lac Ste. Anne Co. near Onoway and Lac Ste. Anne, AB',
    '76231': 'Parkland Co. near Entwistle Fallis and Tomahawk, AB',
    '76232': 'Parkland Co. near Wabamun Carvel and Keephills, AB',
    '76233': 'Parkland Co. near Spruce Grove and Stony Plain, AB',
    '76241': 'Sturgeon Co. near Rivière Qui Barre and Villeneuve, AB',
    '76242': 'Sturgeon Co. near Legal and Mearns, AB',
    '76243': 'Sturgeon Co. near Morinville Volmer and Big Lake, AB',
    '76310': 'Thorhild Co. near Thorhild Opal and Radway, AB',
    '76321': 'Sturgeon Co. near Bon Accord Gibbons and Namao, AB',
    '76322': 'Sturgeon Co. near Redwater, AB',
    '76331': 'Lamont Co. near Bruderheim Lamont and Peno Creek, AB',
    '76332': 'Lamont Co. near Andrew and Wostok, AB',
    '76333': 'Lamont Co. near Mundare Chipman and Ukrainian Village, AB',
    '76340': 'Smoky Lake Co. near Smoky Lake and Waskatenau, AB',
    '76350': 'Co. of Two Hills near Willingdon and Hairy Hill, AB',
    '76360': 'Fort Saskatchewan and Nrn Strathcona Co., AB',
    '76370': 'Elk Island Nat. Park, AB',
    '76380': 'Co. of Minburn near Vegreville Inland and Warwick, AB',
    '76400': 'City of Edmonton - St. Albert - Sherwood Park, AB',
    '76510': 'Leduc Co. near Warburg Thorsby and Pigeon Lake, AB',
    '76520': 'Leduc Co. near Calmar and Devon, AB',
    '76530': 'Brazeau Co. near Drayton Valley and Breton, AB',
    '76540': 'Co. of Wetaskiwin near Pigeon Lake, AB',
    '76550': 'Co. of Wetaskiwin near Alder Flats and Winfield, AB',
    '76560': 'Ponoka Co. near Rimbey Bluffton and Hoadley, AB',
    '76570': 'Ponoka Co. near Crestomere, AB',
    '76611': 'Leduc Co. near Leduc Beaumont and Kavanagh, AB',
    '76612': 'Leduc Co. near New Sarepta and Rolly View, AB',
    '76620': 'Co. of Wetaskiwin near Wetaskiwin Millet and Hwy 2, AB',
    '76630': 'Strathcona Co. near Ardrossan and Cooking Lake, AB',
    '76641': 'Beaver Co. near Tofield, AB',
    '76642': 'Beaver Co. near Holden and Ryley, AB',
    '76651': 'Camrose Co. near Hay Lakes and Miquelon Lake Prov. Park, AB',
    '76652': 'Camrose Co. near Camrose and Bittern Lake, AB',
    '76653': 'Camrose Co. near New Norway Edberg and Ferintosh, AB',
    '76654': 'Camrose Co. near Bawlf and Rosalind, AB',
    '76660': 'Flagstaff Co. near Daysland Heisler and Strome, AB',
    '77111': 'Co. of Grande Prairie near Beaverlodge Hythe and Demmitt, AB',
    '77112': 'Co. of Grande Prairie near Sexsmith and La Glace, AB',
    '77113': 'Co. of Grande Prairie near Grande Prairie and Wembley, AB',
    '77121': 'M.D. of Greenview near Wapiti and Shuttler Flats Rec. Area, AB',
    '77122': 'M.D. of Greenview near O\'Brien Prov. Park and Big Mtn Creek, AB',
    '77123': 'M.D. of Greenview near DeBolt, AB',
    '77124': 'M.D. of Greenview near Little Smoky, AB',
    '77125': 'M.D. of Greenview near Sturgeon Lake, AB',
    '77126': 'M.D. of Greenview near Valleyview and New Fish Creek, AB',
    '77210': 'M.D. of Greenview near Grande Cache Botten and Amundson, AB',
    '77220': 'M.D. of Greenview near Kakwa Wildland Prov. Park and Nose Lake, AB',
    '77230': 'Yellowhead Co. near William A. Switzer Prov. Park, AB',
    '77240': 'Yellowhead Co. near Big Berland and the Wildhay River, AB',
    '77250': 'Willmore Wilderness Park, AB',
    '77260': 'Yellowhead Co. near Hinton and Obed Lake Prov. Park, AB',
    '77311': 'Big Lakes County near Enilda and Joussard, AB',
    '77312': 'Big Lakes County near Hilliard\'s Bay Prov. Park and Big Point, AB',
    '77313': 'Big Lakes County near Driftpile Faust and Kinuso, AB',
    '77321': 'M.D. of Lesser Slave River near Slave Lake and Saulteaux, AB',
    '77322': 'M.D. of Lesser Slave River near Marten Beach, AB',
    '77323': 'M.D. of Lesser Slave River near Smith and Fawcett Lake, AB',
    '77330': 'M.D. of Opportunity near Calling and Rock Island Lakes, AB',
    '77340': 'Athabasca Co. near Wandering River, AB',
    '77410': 'M.D. of Greenview near Fox Creek, AB',
    '77421': 'Yellowhead Co. near Edson and Sundance Prov. Park, AB',
    '77422': 'Yellowhead Co. near Peers and Niton Junction, AB',
    '77431': 'Woodlands Co. near Benbow and Windfall, AB',
    '77432': 'Woodlands Co. near Carson-Pegasus Prov. Park, AB',
    '77433': 'Woodlands Co. near Goose Lake, AB',
    '77434': 'Woodlands Co. near Whitecourt and Blue Ridge, AB',
    '77440': 'Big Lakes County near Swan Hills, AB',
    '78111': 'Mackenzie Co. near Bistcho Lake, AB',
    '78112': 'Mackenzie Co. near Rainbow Lake Zama Lake and Chateh, AB',
    '78113': 'Mackenzie Co. near Zama City, AB',
    '78114': 'Mackenzie Co. near Indian Cabins and Steen River, AB',
    '78115': 'Mackenzie Co. near Meander River and Lutose, AB',
    '78116': 'Mackenzie Co. near High Level and Bushe River Res., AB',
    '78120': 'Co. of Northern Lights near Paddle Prairie Smt, AB',
    '78131': 'Mackenzie Co. near the Caribou Mountains, AB',
    '78132': 'Mackenzie Co. near Fort Vermilion, AB',
    '78133': 'Mackenzie Co. near John D\'or Prairie and Fox Lake, AB',
    '78134': 'Mackenzie Co. near La Crête and Buffalo Head Prairie, AB',
    '78135': 'Mackenzie Co. near the Tallcree and Wadlin Lake Reserves, AB',
    '78211': 'Clear Hills Co. near Chinchaga Wildland Prov. Park, AB',
    '78212': 'Clear Hills Co. near Cleardale Worsley and Cherry Point, AB',
    '78213': 'Clear Hills Co. near Hines Creek and Eureka River, AB',
    '78221': 'Saddle Hills Co. near Bay Tree and Silver Valley, AB',
    '78222': 'Saddle Hills Co. near Moonshine Lake Prov. Park, AB',
    '78223': 'Saddle Hills Co. near Woking, AB',
    '78231': 'M.D. of Spirit River including Spirit River and Rycroft, AB',
    '78232': 'M.D. of Fairview including Fairview Whitelaw and Dunvegan, AB',
    '78233': 'M.D. of Peace including Grimshaw and Berwyn, AB',
    '78241': 'Co. of Northern Lights near Manning and Notikewin Prov. Park, AB',
    '78242': 'Co. of Northern Lights near Dixonville and Cardinal Lake, AB',
    '78251': 'Birch Hills Co. near Wanham and Peoria, AB',
    '78252': 'Birch Hills Co. near Eaglesham and Hwy 740, AB',
    '78261': 'Nrn Sunrise Co. near Keppler Creek, AB',
    '78262': 'Nrn Sunrise Co. near Peace River Nampa and Three Creeks, AB',
    '78270': 'M.D. of Smoky River including Falher McLennan and Guy, AB',
    '78280': 'Big Lakes County near High Prairie and Winagami Lake, AB',
    '78311': 'Nrn Sunrise Co. near Loon Prairie Res. and Bison Lake, AB',
    '78312': 'Nrn Sunrise Co. near Cadotte Lake and Swampy Lake Res., AB',
    '78313': 'Nrn Sunrise Co. near Utikoomak Reserves, AB',
    '78320': 'Big Lakes County near Gift Lake and Peavine Smts, AB',
    '78331': 'M.D. of Opportunity near Peerless Lake and Trout Lake, AB',
    '78332': 'M.D. of Opportunity near Red Earth Creek and Loon Lake, AB',
    '78333': 'M.D. of Opportunity near Wabasca-Desmarais and Sandy Lake, AB',
    '78334': 'M.D. of Opportunity near Chipewyan Lake, AB',
    '79111': 'Wood Buffalo Nat. Park west of the Fifth Meridian, AB',
    '79112': 'Wood Buffalo Nat. Park near Hay Camp and Ninishith Hills, AB',
    '79113': 'Wood Buffalo Nat. Park near Garden River and Thebacha Trail, AB',
    '79114': 'Wood Buffalo Nat. Park near Peace Point and Lake Claire, AB',
    '79121': 'R.M. of Wood Buffalo near Namur River and Namur Lake Reserves, AB',
    '79122': 'R.M. of Wood Buffalo near Clausen\'s Landing and Chipewyan 201FG, AB',
    '79123': 'R.M. of Wood Buffalo near Old Fort Chipewyan 201 and 201ABCDE, AB',
    '79131': 'R.M. of Wood Buffalo near Fitzgerald and La Butte Creek, AB',
    '79132': 'R.M. of Wood Buffalo near Colin-Cornwall Lakes Prov. Park, AB',
    '79133': 'R.M. of Wood Buffalo near Fort Chipewyan and Sand Point, AB',
    '79210': 'R.M. of Wood Buffalo near Fort MacKay and Wallace Creek, AB',
    '79221': 'R.M. of Wood Buffalo near Fort McMurray and Anzac, AB',
    '79222': 'R.M. of Wood Buffalo near Gipsy Lake and Whitemud Falls, AB',
    '79223': 'R.M. of Wood Buffalo near Grand Rapids Wildland Prov. Park, AB',
    '79231': 'R.M. of Wood Buffalo near Mariana Lake, AB',
    '79232': 'R.M. of Wood Buffalo near Stony Mtn Prov. Park and Engstrom Lake, AB',
    '79241': 'Lac La Biche Co. near Crow Lake Prov. Park, AB',
    '79242': 'Lac La Biche Co. near Wiau Winefred and Grist Lakes, AB',
    '79243': 'R.M. of Wood Buffalo near Janvier South and Conklin, AB',
    '81100': 'Haida Gwaii, BC',
    '81200': 'North Vancouver Island, BC',
    '81310': 'East Vancouver Island - Duncan to Nanaimo, BC',
    '81320': 'East Vancouver Island - Nanoose Bay to Fanny Bay, BC',
    '81330': 'East Vancouver Island - Courtenay to Campbell River, BC',
    '81400': 'West Vancouver Island, BC',
    '81500': 'Inland Vancouver Island, BC',
    '81600': 'Greater Victoria, BC',
    '82100': 'Central Coast - coastal sections, BC',
    '82200': 'Central Coast - inland sections, BC',
    '82310': 'Sunshine Coast - Gibsons to Earls Cove, BC',
    '82320': 'Sunshine Coast - Saltery Bay to Powell River, BC',
    '82400': 'Whistler, BC',
    '82511': 'Howe Sound, BC',
    '82512': 'Metro Vancouver - North Shore including West Vancouver and North Vancouver, BC',
    '82513': 'Metro Vancouver - northeast including Coquitlam and Maple Ridge, BC',
    '82514': 'Howe Sound, BC',
    '82520': 'Howe Sound, BC',
    '82610': 'Metro Vancouver - North Shore including West Vancouver and North Vancouver, BC',
    '82620': 'Metro Vancouver - central including the City of Vancouver Burnaby and New Westminster, BC',
    '82630': 'Metro Vancouver - northeast including Coquitlam and Maple Ridge, BC',
    '82640': 'Metro Vancouver - southeast including Surrey and Langley, BC',
    '82650': 'Metro Vancouver - southwest including Richmond and Delta, BC',
    '82711': 'Fraser Valley - west including Abbotsford, BC',
    '82712': 'Fraser Valley - west including Abbotsford, BC',
    '82713': 'Metro Vancouver - southeast including Surrey and Langley, BC',
    '82714': 'Metro Vancouver - northeast including Coquitlam and Maple Ridge, BC',
    '82721': 'Fraser Valley - central including Chilliwack, BC',
    '82722': 'Fraser Valley - central including Chilliwack, BC',
    '82723': 'Manning - Skagit Valley, BC',
    '82730': 'Fraser Valley - east including Hope, BC',
    '82800': 'Southern Gulf Islands, BC',
    '83110': 'Fraser Canyon - north including Lillooet, BC',
    '83121': 'Nicola, BC',
    '83122': 'Fraser Canyon - south including Lytton, BC',
    '83200': 'South Thompson, BC',
    '83300': 'Nicola, BC',
    '83410': 'Manning - Skagit Valley, BC',
    '83420': 'Similkameen, BC',
    '83510': 'North Okanagan - including Vernon, BC',
    '83520': 'Central Okanagan - including Kelowna, BC',
    '83530': 'South Okanagan - including Penticton, BC',
    '83600': 'Shuswap, BC',
    '84100': 'Arrow Lakes - Slocan Lake, BC',
    '84200': 'Boundary, BC',
    '84300': 'West Kootenay, BC',
    '84400': 'Kootenay Lake, BC',
    '84510': 'East Kootenay - south including Cranbrook, BC',
    '84520': 'East Kootenay - north including Invermere, BC',
    '84600': 'Elk Valley, BC',
    '85100': 'North Thompson, BC',
    '85200': 'North Columbia, BC',
    '85300': 'Kinbasket, BC',
    '85400': 'West Columbia, BC',
    '85500': 'East Columbia, BC',
    '85600': 'Yoho Park - Kootenay Park, BC',
    '86100': 'Chilcotin, BC',
    '86210': 'Cariboo - north including Quesnel, BC',
    '86220': 'Cariboo - south including Williams Lake, BC',
    '86300': '100 Mile, BC',
    '86400': 'Yellowhead, BC',
    '87110': 'Bulkley Valley, BC',
    '87120': 'Lakes District, BC',
    '87200': 'Williston, BC',
    '87310': 'B.C. South Peace River, BC',
    '87320': 'B.C. North Peace River, BC',
    '87410': 'Stuart - Nechako, BC',
    '87420': 'Prince George, BC',
    '87500': 'McGregor, BC',
    '88100': 'Fort Nelson, BC',
    '88200': 'Muncho Lake Park - Stone Mountain Park, BC',
    '88300': 'Watson Lake, BC',
    '89100': 'North Coast - coastal sections, BC',
    '89210': 'North Coast - inland including Terrace, BC',
    '89220': 'North Coast - inland including Kitimat, BC',
    '89230': 'North Coast - inland including Stewart, BC',
    '89300': 'Dease Lake, BC',
    '89400': 'Cassiar Mountains, BC',
    '89500': 'Teslin, BC',
    '89600': 'Atlin, BC',
    '91100': 'Dawson, YT',
    '91200': 'Mayo, YT',
    '91300': 'Beaver Creek, YT',
    '91400': 'Pelly - Carmacks, YT',
    '91500': 'Kluane Lake, YT',
    '91600': 'Haines Junction, YT',
    '91700': 'Whitehorse, YT',
    '92100': 'Teslin, YT',
    '92200': 'Cassiar Mountains, YT',
    '92300': 'Watson Lake, YT',
    '92400': 'Faro - Ross River, YT',
    '93100': 'Dempster, YT',
    '93200': 'Old Crow, YT',
    '94200': 'Ft. Liard Region including Nahanni Butte - Sambaa K\'e, NT',
    '94300': 'Ft. Simpson Region including Jean Marie River, NT',
    '94400': 'Wrigley Region, NT',
    '94500': 'Norman Wells - Tulita Region, NT',
    '94600': 'Fort Good Hope Region, NT',
    '94710': 'Deline, NT',
    '94720': 'Colville Lake, NT',
    '95200': 'Ft. Providence Region including Kakisa - Chan Lake, NT',
    '95310': 'Yellowknife Region, NT',
    '95320': 'North Slave Region including Wekweeti - Whati - Behchoko, NT',
    '95400': 'Hay River Region including Enterprise, NT',
    '95500': 'Thebacha Region including Ft. Smith - Salt River Reserve, NT',
    '95600': 'Ft. Resolution Region including Hwy. 6, NT',
    '95700': 'Lutsel K\'e Region, NT',
    '96210': 'Sachs Harbour, NT',
    '96310': 'Ulukhaktok, NT',
    '96420': 'Paulatuk, NT',
    '96520': 'Tuktoyaktuk - East Channel Region, NT',
    '96530': 'Aklavik Region, NT',
    '96540': 'Inuvik Region, NT',
    '96550': 'South Delta Region including Ft. McPherson - Tsiigehtchic, NT',
    '97110': 'Cambridge Bay, NU',
    '97210': 'Kugluktuk, NU',
    '97310': 'Taloyoak, NU',
    '97410': 'Gjoa Haven, NU',
    '97420': 'Kugaaruk, NU',
    '97510': 'Baker Lake, NU',
    '97610': 'Arviat, NU',
    '97620': 'Rankin Region including Whale Cove, NU',
    '97630': 'Chesterfield Inlet, NU',
    '97710': 'Sanirajak, NU',
    '97720': 'Igloolik, NU',
    '97730': 'Naujaat, NU',
    '97810': 'Coral Harbour, NU',
    '97910': 'Sanikiluaq, NU',
    '98110': 'Arctic Bay, NU',
    '98120': 'Pond Inlet, NU',
    '98130': 'Clyde River, NU',
    '98210': 'Qikiqtarjuaq, NU',
    '98220': 'Pangnirtung, NU',
    '98230': 'Iqaluit, NU',
    '98240': 'Kimmirut, NU',
    '98250': 'Kinngait, NU',
    '99110': 'Resolute, NU',
    '99210': 'Grise Fiord, NU',
}

def decode_ca_area(code):
    """Decodifica un código PSSCCC canadiense."""
    if len(code) < 6:
        return code, "Unknown"
    SS = code[1:3]
    SSCCC = code[1:]
    entry = CA_SAME_CODE.get(SSCCC)
    if entry:
        if ", " in entry:
            parts = entry.rsplit(", ", 1)
            return parts[0], parts[1]
        return entry, "Canada"
    state = CA_PROVINCES.get(SS, f"Province {SS}")
    return f"Area {SSCCC}", state
